name: devices_data_source
description: A generic interface for managing devices.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: '>=3.3.0'

dependencies:
  commons_ntt_device_dbe:
    path: ../commons_ntt_device_dbe
  dependencies:
    path: ../dependencies
  ntt_device_models:
    path: ../ntt_device_models

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
