name: ntt_device_models
description: Common list of model shared between FE and DBE
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: '>=3.3.0'

dependencies:
  dependencies:
    path: ../dependencies

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
